/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SideDrawer {
        "close": () => Promise<void>;
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface ZLoader {
    }
    interface ZStockFinder {
    }
    interface ZStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSideDrawerElement extends Components.SideDrawer, HTMLStencilElement {
    }
    var HTMLSideDrawerElement: {
        prototype: HTMLSideDrawerElement;
        new (): HTMLSideDrawerElement;
    };
    interface HTMLZLoaderElement extends Components.ZLoader, HTMLStencilElement {
    }
    var HTMLZLoaderElement: {
        prototype: HTMLZLoaderElement;
        new (): HTMLZLoaderElement;
    };
    interface HTMLZStockFinderElement extends Components.ZStockFinder, HTMLStencilElement {
    }
    var HTMLZStockFinderElement: {
        prototype: HTMLZStockFinderElement;
        new (): HTMLZStockFinderElement;
    };
    interface HTMLZStockPriceElement extends Components.ZStockPrice, HTMLStencilElement {
    }
    var HTMLZStockPriceElement: {
        prototype: HTMLZStockPriceElement;
        new (): HTMLZStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "side-drawer": HTMLSideDrawerElement;
        "z-loader": HTMLZLoaderElement;
        "z-stock-finder": HTMLZStockFinderElement;
        "z-stock-price": HTMLZStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface ZLoader {
    }
    interface ZStockFinder {
        "onZSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface ZStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "side-drawer": SideDrawer;
        "z-loader": ZLoader;
        "z-stock-finder": ZStockFinder;
        "z-stock-price": ZStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "side-drawer": LocalJSX.SideDrawer & JSXBase.HTMLAttributes<HTMLSideDrawerElement>;
            "z-loader": LocalJSX.ZLoader & JSXBase.HTMLAttributes<HTMLZLoaderElement>;
            "z-stock-finder": LocalJSX.ZStockFinder & JSXBase.HTMLAttributes<HTMLZStockFinderElement>;
            "z-stock-price": LocalJSX.ZStockPrice & JSXBase.HTMLAttributes<HTMLZStockPriceElement>;
        }
    }
}
