/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FooBar {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TodoComponent {
    }
}
declare global {
    interface HTMLFooBarElement extends Components.FooBar, HTMLStencilElement {
    }
    var HTMLFooBarElement: {
        prototype: HTMLFooBarElement;
        new (): HTMLFooBarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTodoComponentElement extends Components.TodoComponent, HTMLStencilElement {
    }
    var HTMLTodoComponentElement: {
        prototype: HTMLTodoComponentElement;
        new (): HTMLTodoComponentElement;
    };
    interface HTMLElementTagNameMap {
        "foo-bar": HTMLFooBarElement;
        "my-component": HTMLMyComponentElement;
        "todo-component": HTMLTodoComponentElement;
    }
}
declare namespace LocalJSX {
    interface FooBar {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TodoComponent {
    }
    interface IntrinsicElements {
        "foo-bar": FooBar;
        "my-component": MyComponent;
        "todo-component": TodoComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "foo-bar": LocalJSX.FooBar & JSXBase.HTMLAttributes<HTMLFooBarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "todo-component": LocalJSX.TodoComponent & JSXBase.HTMLAttributes<HTMLTodoComponentElement>;
        }
    }
}
